version: "3.2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: volume
        source: arcanaeum_data
        target: /go/src/arcanaeum/data
        volume:
          nocopy: true
    logging:
      driver: journald
      options:
        tag: arcanaeumlog
    restart: always
    # networks:
    #   - webnet
# networks:
#   webnet:
volumes:
  arcanaeum_data:
