version: "3.2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafapp
      MYSQL_USER: cafapp
      MYSQL_PASSWORD: cafapp
  web:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - "db"
    logging:
      driver: journald
      options:
        tag: cafapplog
    restart: always

